# Application Name
spring.application.name=StudentDualDBApp

# H2 Database Configuration
spring.datasource.h2.url=jdbc:h2:mem:h2db
spring.datasource.h2.username=sa
spring.datasource.h2.password=
spring.datasource.h2.driver-class-name=org.h2.Driver

# PostgreSQL Database Configuration
spring.datasource.pg.url=jdbc:postgresql://localhost:5432/studentdb
spring.datasource.pg.username=postgres
spring.datasource.pg.password=postgres
spring.datasource.pg.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# H2 Console Configuration
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

# Thymeleaf Configuration
spring.thymeleaf.cache=false
